hydra:
  searchpath:
    - pkg://verl.trainer.config

defaults:
  - ppo_trainer
  - override model_engine: megatron
  - _self_

algorithm:
  adv_estimator: rloo_vectorized
  norm_adv_by_std_in_grpo: false
  filter_groups:
    enable: true
    metric: acc
    min: 0.0
    max: 1.0

  rollout_correction:
    bypass_mode: true

data:
  apply_chat_template_kwargs:
    enable_thinking: false
  train_files: ./data/apertus_demo_rl/train.parquet
  val_files: ./data/apertus_demo_rl/val.parquet
  train_batch_size: 0
  gen_batch_size: 1
  max_prompt_length: 2048
  max_response_length: 4096
  truncation: left

async_training:
  staleness_threshold: 0.2
  trigger_parameter_sync_step: 1
  require_batches: 2
  steady_warmup_steps: 5
  partial_rollout: true
  use_rollout_log_probs: true
  compute_prox_log_prob: false
  use_trainer_do_validate: false
  checkpoint_engine:
    enable: false
    device_buffer_size_M: 4096
    overlap_broadcast_and_consume: false

rollout:
  nnodes: 1
  n_gpus_per_node: 2
  total_rollout_steps: 180000
  total_epochs: ${trainer.total_epochs}

actor_rollout_ref:
  hybrid_engine: false
  nccl_timeout: 1800
  checkpoint_engine: ${oc.select:async_training.checkpoint_engine,null}

  model:
    path: swiss-ai/Apertus-8B-Instruct-2509
    tokenizer_path: null
    use_remove_padding: true
    enable_gradient_checkpointing: true
    use_shm: false
    override_config:
      attn_implementation: flash_attention_2

  actor:
    use_rollout_log_probs: ${oc.select:async_training.use_rollout_log_probs,true}
    ppo_mini_batch_size: 128
    use_dynamic_bsz: true
    ppo_max_token_len_per_gpu: 8192
    calculate_entropy: true

    optim:
      lr: 1e-6
      weight_decay: 0.01
      clip_grad: 1.0
      lr_decay_style: constant

    megatron:
      tensor_model_parallel_size: 4
      pipeline_model_parallel_size: 4
      context_parallel_size: 1
      sequence_parallel: false
      use_distributed_optimizer: true
      use_mbridge: true
      vanilla_mbridge: true
      param_offload: false
      grad_offload: false
      optimizer_offload: false
      override_transformer_config:
        recompute_granularity: full
        recompute_method: uniform
        recompute_num_layers: 1

    clip_ratio_high: 0.28
    clip_ratio_low: 0.2
    use_kl_loss: false
    policy_loss:
      loss_mode: geo_mean
    loss_agg_mode: seq-mean-token-mean
    shuffle: true

  rollout:
    nnodes: ${rollout.nnodes}
    n_gpus_per_node: ${rollout.n_gpus_per_node}
    log_prob_use_dynamic_bsz: true
    log_prob_max_token_len_per_gpu: 32768
    max_num_batched_tokens: 8192
    max_num_seqs: 64
    gpu_memory_utilization: 0.7
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 1
    n: 8
    name: vllm
    mode: async
    calculate_log_probs: true
    checkpoint_engine:
      backend: nccl
      update_weights_bucket_megabytes: 1024
    dtype: bfloat16
    free_cache_engine: true
    enforce_eager: false
    load_format: safetensors
    val_kwargs:
      do_sample: true
      n: 4
      top_p: 0.95
      temperature: 0.7

critic:
  checkpoint:
    save_contents: []

trainer:
  total_epochs: 100
  total_training_steps: 10000
  save_freq: 20
  test_freq: 10
  max_actor_ckpt_to_keep: 10
  max_critic_ckpt_to_keep: null
  project_name: apertus-rl-tests
  experiment_name: GRPO
  logger: [console, wandb]
  nnodes: 1
  n_gpus_per_node: 2
  log_val_generations: 5
  val_before_train: false
  default_local_dir: ./outputs/${trainer.project_name}/${trainer.experiment_name}
  rollout_data_dir: ${trainer.default_local_dir}/rollout/
  validation_data_dir: ${trainer.default_local_dir}/validation/

ray_kwargs:
  ray_init:
    num_cpus: ${oc.decode:${oc.env:SLURM_CPUS_PER_TASK,null}}
  timeline_json_file: null