hydra:
  searchpath:
    - pkg://verl/trainer/config

defaults:
  - ppo_megatron_trainer
  - override model_engine: megatron
  - _self_

async_training:
  staleness_threshold: 0.1
  trigger_parameter_sync_step: 4
  require_batches: 2
  partial_rollout: True
  use_trainer_do_validate: False

rollout:
  nnodes: 1
  n_gpus_per_node: 4
  total_rollout_steps: 180000
  total_epochs: ${trainer.total_epochs}

data:
  apply_chat_template_kwargs:
    enable_thinking: false
  train_batch_size: 0
  gen_batch_size: 1
  max_prompt_length: 2048
  max_response_length: 1024
  truncation: left

actor_rollout_ref:
  hybrid_engine: False

  actor:
    use_rollout_log_probs: ${oc.select:async_training.use_rollout_log_probs,true}
    ppo_mini_batch_size: 128
    use_dynamic_bsz: true
    ppo_max_token_len_per_gpu: 32768
    calculate_entropy: true

    optim:
      lr_decay_steps: 1
      lr_warmup_steps_ratio: 0.2
      lr: 1e-6
      weight_decay: 0.01
      clip_grad: 1.0
      lr_decay_style: constant

    megatron:
      tensor_model_parallel_size: 4
      pipeline_model_parallel_size: 1
      context_parallel_size: 1
      sequence_parallel: false
      use_distributed_optimizer: true
      use_mbridge: true
      vanilla_mbridge: false
      param_offload: false
      grad_offload: false
      optimizer_offload: false
      override_transformer_config:
        recompute_granularity: full
        recompute_method: uniform
        recompute_num_layers: 1

    clip_ratio_high: 0.28
    clip_ratio_low: 0.2
    use_kl_loss: false
    policy_loss:
      loss_mode: geo_mean
    loss_agg_mode: seq-mean-token-mean
    shuffle: true

  rollout:
    nnodes: 1
    n_gpus_per_node: 4
    log_prob_use_dynamic_bsz: true
    log_prob_max_token_len_per_gpu: 32768
    max_num_batched_tokens: 8192
    max_num_seqs: 256
    gpu_memory_utilization: 0.7
    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 1
    n: 8
    name: sglang
    mode: async
    calculate_log_probs: true
    checkpoint_engine:
      backend: nccl
      update_weights_bucket_megabytes: 1024
    dtype: bfloat16
    free_cache_engine: true
    enforce_eager: false
    load_format: dummy
    val_kwargs:
      do_sample: true
      n: 4
      top_p: 0.95
      temperature: 0.7
 
  model:
    path: /capstor/store/cscs/swissai/infra01/apertus_1p5/hf_checkpoints/ap1p5-8b-sft-256k-adam-lr6e-5-constant-128n_4200
    tokenizer_path: /capstor/store/cscs/swissai/infra01/apertus_1p5/hf_checkpoints/ap1p5-8b-sft-256k-adam-lr6e-5-constant-128n_4200
    use_remove_padding: true
    enable_gradient_checkpointing: false
    use_shm: false
    override_config:
      attn_implementation: flash_attention_2

# Only then will the use of log probs be correct.
# And it can be used in conjunction with other rollout_correction algorithms.
algorithm:
  adv_estimator: rloo_vectorized
  norm_adv_by_std_in_grpo: false
  filter_groups:
    enable: true
    metric: acc
    min: 0.0
    max: 1.0
critic:
  checkpoint:
    save_contents: []


trainer:
  total_epochs: 10
  total_training_steps: 500000
  save_freq: 50
  test_freq: 10
  max_actor_ckpt_to_keep: 10
  max_critic_ckpt_to_keep: null
  project_name: multi-node-rl-test
  # experiment_name: GRPO
  logger: [console]
  nnodes: 1
  n_gpus_per_node: 4
  log_val_generations: 5
  val_before_train: false
  default_local_dir: ./outputs/${trainer.project_name}/${trainer.experiment_name}
  rollout_data_dir: ${trainer.default_local_dir}/rollout/
  validation_data_dir: ${trainer.default_local_dir}/validation/

ray_kwargs:
  ray_init:
    num_cpus: ${oc.decode:${oc.env:SLURM_CPUS_PER_TASK,null}}
  timeline_json_file: null